version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###
  php:
    container_name: php
    build:
      context: .
    ports:
      - '8080:8080'
    volumes:
      - .:/var/www/pigz_api
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for-it.sh database:5432 --
        php bin/console make:migration --no-interaction
        php bin/console doctrine:migrations:migrate --no-interaction
        php -S 0.0.0.0:8080 -t public/
    depends_on:
      - database

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
